apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: featurehelm #argocdproj-name
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Girija-Sugumar/helm-task.git'
    path: congigchange #helm-chart name
    targetRevision: HEAD #branchname
    helm:
     valueFiles:
      - values.yaml
     parameters:
      - name: "env"
        value: feature #envname 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
     prune: true
     selfHeal: true