apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: featurehelm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Girija-Sugumar/helm-task.git'
    path: congigchange
    targetRevision: HEAD
    helm:
     valueFiles:
      - values.yaml
     parameters:
      - name: "env"
        value: feature
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
     prune: true
     selfHeal: true