app:
  deploymentName: api-tester-app
  image: nginx
  imagePullPolicy: Always
  port: 9000
  restartPolicy: Always
  strategy: RollingUpdate
  targetPort: 9000

nginx:
  deploymentName: api-tester-nginx
  replicas: 1
  strategy: RollingUpdate
  imagePullPolicy: Always
  restartPolicy: Always
  port: 80
  targetPort: 80

db:
  deploymentName: api-tester-db
  image: "mysql:8.0.32"
  replicas: 1
  strategy: Recreate
  imagePullPolicy: Never
  restartPolicy: Always
  port: 3306
  targetPort: 3306
  volumesName: api-tester
  volumeMountsName: api-tester

# redis:
#   image: "redis:7.0.9-alpine3.17"
#   deploymentName: api-tester-redis
#   replicas: 1
#   strategy: Recreate
#   imagePullPolicy: Never
#   restartPolicy: Always
#   port: 6379
#   targetPort: 6379

pvc:
  name: api-tester
  storage: 500Mi

ingress:
  name: api-tester
  prefixDomain: api-tester
  serviceOne:
    name: api-tester-nginx
    port: 80

configName: api-tester
secretName: api-tester
imagePullSecrets: 'gitlab-token-all-waymore'

env: 'feature'
environments:
  feature:
    namespace: "feature"
    tag: "feature"
    nginxTag: "nginx-feature"
    configmap:
      APP_NAME: "api-testing"
      APP_ENV: "feature"
      APP_KEY: "QmJCEOkLu3OfvVrJGLM86vTFo6A3OHC1"
      APP_URL: "https://api-tester.feature.env.waymore.io/"
      APP_DEBUG: "true"

      LOG_CHANNEL: "stack"

      CORS_ALLOWED_ORIGINS: "*"
      CORS_ALLOWED_METHODS: "GET , POST, DELETE, PUT, PATCH, OPTIONS"
      CORS_ALLOWED_HEADERS: "Content-Type, Authorization"
      CORS_PATHS: "api/*"
      CORS_EXPOSED_HEADERS: "content-disposition"

      CACHE_DRIVER: "file"
      QUEUE_CONNECTION: "sync"
      BROADCAST_DRIVER: "log"
      SESSION_DRIVER: "file"
      SESSION_LIFETIME: "120"

    secrets:
      DB_CONNECTION: "mysql"
      DB_HOST: "api-tester-db"
      DB_DATABASE: "routee_live_test"
      DB_USERNAME: "test_price_api_usr23"
      DB_PASSWORD: "OFh<9>[#O&"
      DB_PORT: "3306"

      REDIS_HOST: "api-tester-redis"
      REDIS_PASSWORD: ""
      REDIS_PORT: "6379"

      MAIL_MAILER: "smtp"
      MAIL_HOST: "mailhog"
      MAIL_PORT: "1025"
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: ""

      PUSHER_APP_ID: ""
      PUSHER_APP_KEY: ""
      PUSHER_APP_SECRET: ""
      PUSHER_APP_CLUSTER: "mt1"

      MIX_PUSHER_APP_KEY: ""
      MIX_PUSHER_APP_CLUSTER: ""

      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
      MYSQL_DATABASE: "routee_live_test"
      MYSQL_PASSWORD: "OFh<9>[#O&"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "OFh<9>[#O&"
      MYSQL_USER: "test_price_api_usr"

    request:
      cpu: 10m
      memory: 50M
    ingress:
      baseDomain: feature.env.waymore.io

  staging:
    namespace: "staging"
    tag: "staging"
    nginxTag: "nginx-staging"
    configmap:
      APP_NAME: "api-tester"
      APP_ENV: "staging"
      APP_KEY: "QmJCEOkLu3OfvVrJGLM86vTFo6A3OHC1"
      APP_URL: "https://api-tester.staging.env.waymore.io/"
      APP_DEBUG: "true"

      LOG_CHANNEL: "stack"

      CORS_ALLOWED_ORIGINS: "*"
      CORS_ALLOWED_METHODS: "GET , POST, DELETE, PUT, PATCH, OPTIONS"
      CORS_ALLOWED_HEADERS: "Content-Type, Authorization"
      CORS_PATHS: "api/*"
      CORS_EXPOSED_HEADERS: "content-disposition"

      CACHE_DRIVER: "file"
      QUEUE_CONNECTION: "sync"
      BROADCAST_DRIVER: "log"
      SESSION_DRIVER: "file"
      SESSION_LIFETIME: "120"

    secrets:
      DB_CONNECTION: "mysql"
      DB_HOST: "api-tester-db"
      DB_DATABASE: "routee_live_test"
      DB_USERNAME: "test_price_api_usr"
      DB_PASSWORD: "OFh<9>[#O&"
      DB_PORT: "3306"

      REDIS_HOST: "redis"
      REDIS_PASSWORD: ""
      REDIS_PORT: "6379"

      MAIL_MAILER: "smtp"
      MAIL_HOST: "mailhog"
      MAIL_PORT: "1025"
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: ""

      PUSHER_APP_ID: ""
      PUSHER_APP_KEY: ""
      PUSHER_APP_SECRET: ""
      PUSHER_APP_CLUSTER: "mt1"

      MIX_PUSHER_APP_KEY: ""
      MIX_PUSHER_APP_CLUSTER: ""

      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
      MYSQL_DATABASE: "routee_live_test"
      MYSQL_PASSWORD: "OFh<9>[#O&"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "OFh<9>[#O&"
      MYSQL_USER: "test_price_api_usr"

    request:
      cpu: 10m
      memory: 50M
      
    ingress:
      baseDomain: staging.env.waymore.io

