apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configName }}
  namespace: {{ index .Values.environments .Values.env "namespace" }}
data:
  APP_NAME: '{{ index .Values.environments .Values.env "configmap" "APP_NAME" }}'
  APP_ENV: '{{ index .Values.environments .Values.env "configmap" "APP_ENV" }}'
  APP_URL: '{{ index .Values.environments .Values.env "configmap" "APP_URL" }}'
  APP_DEBUG: '{{ index .Values.environments .Values.env "configmap" "APP_DEBUG" }}'
  APP_KEY: '{{ index .Values.environments .Values.env "configmap" "APP_KEY" }}' 