apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ index .Values.environments .Values.env "namespace" }}   
type: Opaque
data:
  DB_CONNECTION: {{ index .Values.environments .Values.env "secrets" "DB_CONNECTION" | b64enc }}
  DB_HOST: {{ index .Values.environments .Values.env "secrets" "DB_HOST" | b64enc }}
  DB_DATABASE: {{ index .Values.environments .Values.env "secrets" "DB_DATABASE" | b64enc }}
  DB_USERNAME: {{ index .Values.environments .Values.env "secrets" "DB_USERNAME" | b64enc }}
  DB_PASSWORD: {{ index .Values.environments .Values.env "secrets" "DB_PASSWORD" | b64enc }}
  